//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Fonlow.CommandLineGui.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Fonlow.CommandLineGui.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} must be greater than zero.
        /// </summary>
        internal static string ArgMustBeGreaterThanZero {
            get {
                return ResourceManager.GetString("ArgMustBeGreaterThanZero", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} must be non-negative.
        /// </summary>
        internal static string ArgMustBeNonNegative {
            get {
                return ResourceManager.GetString("ArgMustBeNonNegative", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to \w+([\.]\w+)*
        ///|(&quot;(([a-zA-Z]:)|(\\\\[^/\\:\*\?&quot;&quot;&lt;&gt;\|]+(\\[a-zA-Z]\$)?))\\([^/\\:\*\?&quot;&quot;&lt;&gt;\|]+\\)*[^/\\:\*\?&quot;&quot;&lt;&gt;\|]+(\.[^/\\:\*\?&quot;&quot;&lt;&gt;\|]+[^/\\:\*\?&quot;&quot;&lt;&gt;\|\s])?&quot;)
        ///|((([a-zA-Z]:)|(\\\\[^/\\:\*\?&quot;&quot;&lt;&gt;\|\s]+(\\[a-zA-Z]\$)?))\\([^/\\:\*\?&quot;&quot;&lt;&gt;\|\s]+\\)*[^/\\:\*\?&quot;&quot;&lt;&gt;\|\s]+(\.[a-zA-Z0-9]+)?).
        /// </summary>
        internal static string filePathPattern {
            get {
                return ResourceManager.GetString("filePathPattern", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Internal error; Unimplemented VerticalAlignment used.
        /// </summary>
        internal static string InternalErrorUnimplementedVerticalAlignmentUsed {
            get {
                return ResourceManager.GetString("InternalErrorUnimplementedVerticalAlignmentUsed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Options:.
        /// </summary>
        internal static string Options {
            get {
                return ResourceManager.GetString("Options", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to version.
        /// </summary>
        internal static string Version {
            get {
                return ResourceManager.GetString("Version", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to width must not be less than {0}.
        /// </summary>
        internal static string WidthMustNotBeLessThan0 {
            get {
                return ResourceManager.GetString("WidthMustNotBeLessThan0", resourceCulture);
            }
        }
    }
}
