using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;

namespace Fonlow.CommandLine
{
    /// <summary>
    /// Decorate some properties of the proxy class generated by this framework. Applications and plugins should not use this property.
    /// </summary>
    [AttributeUsage(AttributeTargets.Property, AllowMultiple = false)]
    public sealed class ParameterOrderAttribute : Attribute
    {
        public ParameterOrderAttribute(int order)
        {
            Order = order;
        }

        public int Order { get; private set; }
    }

    /// <summary>
    /// Decorate properties of fixed parameters.
    /// </summary>
    [AttributeUsage(AttributeTargets.Property | AttributeTargets.Field)]
    public sealed class FixedParameterAttribute : System.Attribute
    {
        public string DisplayName { get; set; }

        public string Description { get; set; }

        public string Category { get; set; }

        /// <summary>
        /// Should be between 1..n representing the order of fixed parameters. The order numbers of attributes should be unique within the class.
        /// </summary>
        public int Order { get; set; }

        public object DefaultValue { get; set; }
    }

}
